import type { Metadata } from "next";
import localFont from "next/font/local";
import Script from "next/script";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
      <Script src="https://telegram.org/js/tele-web-app.js" strategy="afterInteractive" />
        <div className="w-full flex justify-between fixed bottom-0 left-0 right-0 bg-slate-600 p-3">
          <Link href="/">Home</Link>
          <Link href="/plant">Plant</Link>
          <Link href="/friend">Friend</Link>
          <Link href="/reward">Reward</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
